name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Install Garble
        run: |
          go install mvdan.cc/garble@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build with Garble
        run: |
          mkdir -p build_assets
          # 获取版本 ID
          COMMID=$(git describe --always --dirty || echo "custom-build")
          
          # 核心混淆编译命令
          garble -literals -tiny build \
            -o build_assets/xray \
            -trimpath \
            -buildvcs=false \
            -ldflags="-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" \
            -v ./main

      - name: UPX Compression
        run: |
          sudo apt-get install -y upx-ucl
          upx --lzma --best --force build_assets/xray

      # --- 如果是 Release 发布，直接上传二进制文件到 Release 页面 ---
      - name: Upload Binary to Release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_assets/xray
          asset_name: xray-${{ matrix.goos }}-${{ matrix.goarch }}
          tag: ${{ github.ref }}
          overwrite: true

      # --- 无论什么触发方式，都上传到 Actions Artifacts 方便直接下载 ---
      - name: Upload Binary to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Xray-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build_assets/xray
          retention-days: 5
