name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install UPX
        run: sudo apt-get install -y upx-ucl

      - name: Build and UPX
        run: |
          mkdir -p build_assets
          COMMID=$(git describe --always --dirty)
          
          # 执行编译（只产出核心二进制）
          go build -o build_assets/xray -trimpath -buildvcs=false -gcflags="all=-l=4" -ldflags="-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" -v ./main
          
          # 执行 UPX 压缩
          upx --lzma --best build_assets/xray

      - name: Create ZIP archive
        if: github.event_name == 'release'
        shell: bash
        run: |
          # 只压缩 build_assets 里的核心文件
          pushd build_assets || exit 1
          # 仅打包 xray 那个文件，不打包整个目录
          zip -9j ../Xray-${{ matrix.goos }}-${{ matrix.goarch }}.zip xray
          popd || exit 1

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Xray-*.zip
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Xray-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build_assets/xray
